version: "3.8"

# Add this at the top level (same level as services)
x-buildkit: &buildkit
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

# Security Note: The ollama service has internet access to download models from registry.ollama.ai
# The open-webui service is isolated from the internet but can communicate with ollama
# For maximum security, consider downloading models manually and removing internet access

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./modelfiles:/app/modelfiles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_ALIVE=24h
    dns:
      - 8.8.8.8
    restart: unless-stopped
    networks:
      - ollama-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - openwebui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - WEBUI_AUTH=False
      - WEBUI_NAME=GPT-OSS-WebUI
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
    internal: false
    driver_opts:
      com.docker.network.bridge.name: ollama-br0

volumes:
  ollama_data:
  openwebui_data:
